services:
  - type: web
    name: crazytime-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
